const themeForm = {
  label: 'Theme',
  fields: [
    ...[
      'primary',
      'secondary',
      'accent',
      'success',
      'warning',
      'ui.bright',
      'ui.light',
      'ui.whisper',
      'code',
      'gray.dark',
      'gray.calm',
      'white',
      'black',
    ].map(color => ({
      name: `rawJson.colors.${color}`,
      component: 'color',
      label: `Theme ${color} color`,
      description: `Edit the theme ${color} color`,
      colorFormat: 'hex',
    })),
    ...[
      'breakpoints.xs',
      'breakpoints.sm',
      'breakpoints.md',
      'breakpoints.lg',
      'breakpoints.xl',
      'widths.md',
      'widths.lg',
      'widths.xl',
      'fontSize.regular',
      'fontSize.large',
      'headingSizes.h1',
      'headingSizes.h2',
      'headingSizes.h3',
      'headingSizes.h4',
      'lineHeight.regular',
      'lineHeight.heading',
      'containerPadding',
      'heights.header',
    ].map(label => ({
      name: `rawJson.dimensions.${label}`,
      component: 'text',
      label: `Theme dimensions ${label}`,
      description: `Edit the theme ${label} dimension`,
    })),
    ...['sansSerif', 'serif', 'monospace'].map(label => ({
      name: `rawJson.fonts.${label}`,
      component: 'text',
      label: `Theme fonts ${label}`,
      description: `Edit the theme ${label} fonts`,
    })),
  ],
};

export default themeForm;
